[install]
whitelist = ["fat32-model"]

[custom.all.fat32-model]
type = "local"
path = "."
ipkg = "fat32-model.ipkg"

# [idris2]
# type = "github"
# url = "https://github.com/elkcl/Idris2"
# commit = "latest:main"
# ipkg = "idris2.ipkg"

[custom.all.contrib-nat-division]
type = "github"
url = "https://github.com/elkcl/idris2-contrib-nat-division"
commit = "latest:main"
ipkg = "contrib-nat-division.ipkg"

# [custom.all.deptycheck]
# type = "github"
# url = "https://github.com/buzden/deptycheck"
# commit = "5a5174527beb28cc69a19140fc148d682f37ff6f"
# ipkg = "deptycheck.ipkg"
